language: scala

scala:
  - 2.12.4
  - 2.11.12

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: LPUZtuFrYxISfhqHPekYCDxO3fQzwLq/EZJ3fHwu4yMytyxuftcVMp2R4aTUKjK6FhziAdlVvSO/bCrF1i2kEGiHk0t7TEO4RBd2qjWcwzuYWfTzzEcFLu3XK1yCbfrGRLc1xH6JazGm/MF6VxmgIwDPJ3eeciACoZMFoft0KZ1yI/ggft9+c5uvhNGWs7oR/H/VKSFoy6o3BYjRR7GhJL86js+Zy6Tt2ZOBjnSTWfaI7MEGLBC9qeTGMoZqtdGOgbF9znKbrNFx8xl8bTnAh7B60QZOkCxqd/dbv30xY0G1T3nnrdXQDsPpzr6B/xjB8XodQ+nxqJjO5TMP6s0qb5D87oDjO8N7ffrct9F2a0yW41iMurszERKXTUDOgXwktWpq8kquynMgVmbLO5snciJR5O+SiPrg9Uf5kRpDF3bkt8lweRoIrteu94R3HzGyzMZe7xeI61BFyNLfw8njDJbi1G3AqCaTbwmjtIGmWo3NQlEkTNWmMsW3Z41D+/tjqy2oYaX8SuUSEOA+0g055e7iZLrMBPk+Olzw4v2WYcmAcB9LG1hnKzLs4qxPYiGHgqu1hPbDYV9rdvUqH5rdHPOqZhnaFDh4qr3T3/D1CaroPZTAWOAf8z2XVHlU1lg1QtqKhM7irKZ6txLIvWCDhb/WGTJa9UwkOzy0fOQ6ldU=
  - secure: lFJgE6mWC+U0JXtUg+qtICr5ctbq1v2caIhyQJwt5Uzi67Be60HqCSAGgCXftyhuf4su0izI1Hp2Ob1qI43rMmZkJtoxdKNBbqq9963UzHKT5840ZQAk+mtoThbY8P6jSQgt5zilDh8L/MGZas5ZPNyG/Qr+bNqV2yPr2okMHUYvbUSj7dBO9cJlulaMbswzRjHs0zvdDIwM0MD3stQXCs4vcj/XrNmSdxXoxF7luCuMqcq+4EkpnOrlH9ijZKd+j+j+OLW+WiuiX1oaq/rgyx3FQddREWp8u+Id4lOY66tn5HKMUCMUZ7ZjeCv/9R3VcmiLdK3m3FCPhcRie7q7Po2v4RNffq7/Hyrth0s+H/fj8gzRNbr/xxQHu1MQYCYlf6+wocUPpxwm91Mn8Zd2FVzHsT2ZWMMIkq/BsPh3tTSjDX77WVY6MAR9uPda5LotmQpFxfNwNd0ZZDR9X9AQPsl9R9V4lqc8hcMfHoWqIp3Wwq/zc+OLoRtWuxmTPntMPMohYSz9KaPVs222FnpcXBQZBJsl7nSVbedvSHVJxLJeYpxidF4lRbquajdungUYdzW6641f6YQPKM/nwMYmAXG2vgSto4VYGSD2ZexxRnPXhkYdYBT3Rvv0Cg0uRuYlaHm+eYYESslTPB0RYPd41of2mN3DGAzLRi4qvgfvWJA=
  - secure: 208oaHM4uetMRTVYMeNGW3MCQ7K5EYZxN1zB5ojM7MS8VmeGLaJwLHnqicPWg+EvXOtzbC7iMgpqhod3Kh8hkCdJoCjaGoMUcIN3a91K9HlUzgzOW8aFpW66v1DJEl/jrsWKT9DUqMUtZETUq59WI49OST9WbJ11q2uc1cC2HYTfs7Xq41EcVFWsLQkBRIyVV8vHE+FyKr0OAjzmWPHTOOLKj7xtZehSE6djjRNPxCmL7Uracj85daaU600gYSwvKpJJIRv9M70JAq6HCqMx0wb6Is0E3Q2X5OecZ7gmYHxRIF+4KoNbZgX5T3MHX0BFioXJyqpF2voXFv1J2gfm/+1RVIO2uWYOHK5DeOaDtCLMNDBQseU1UjUViqsAyeJqkB/r8MDN0CYoPbF36mRELTvljmm0HvkHosfTS6L5FjxFpBPrfFLVP0BE8eQ59qEoh8yoYW6YFoqahXQqKxuXcIf9DgeFkRUUcoBja9WIW+639sc5cAsUKNZsLAyWA4Fkf5Slra0Z1E4NqyjbZHS1QSUYicccLQGY3yI7qRGDZeA+Qi09zdoJn5k2Vn3Hcc1Tc9Jn97MlvMKgmajgo3KNAfXOX1isQFny9qNiJlyV6a1+fU39ywLJC426XB+D40pTYLYLwju/W9OGRruzb6dtkUxyrBsMyxMQaPj2De8cC4E=
  - secure: gdWKldxlGWzd6NYHf8m7AIjbg5TLjdxcortJLlZOr9ShvId8/O/6HqiA6/P1Ltso8J4ZV7gDFgotUdiVuNZF/8r7dAVaj4A0nTjZ7bwH1xHPcT72mwb9mgyCI1JdKutR93SRKWBLwxSvBYrhzK5X2qCiRTW2KhIHfJLdzbriV/9ZnNBSHLvPIRDYKNph+Eh+DvblqAsge9+Py8601t0MEuopkidPkqt0vIWcisBO4W0ZkPyUb8Ope21+fJUrnL/MMP9hLr2mGXpHskOz1YERbET6/ZgEF2XMuxlasabJCwAg2KkxXwo08lgmTfFySw46O5J44vvsfh2EtLiO511N9rCTjrhlZgCw3vyEhS8J6kagdZToyhC6ex/rUdnxrr57DFppMeORSJtyhFSh+hbYXQLj3ylADHx/uMOPJMX1JHEsXb2HxBw2ZUSdR+XzI8qDFzpUVjhZz28VgMDXS+AHSZ9dya5lE29NvkIEuBnYwhrzDJ6aaGrENAOm4+QLslu6Z8rDnifDISO0sC6iGPQvdqpDCPEjTfyxPH8U+jjehXu45ofyVYrhiDgwlK/ktSVjEwPy+RmcgRTRu1uuotA28h/t28hfjxV6sfjg9zug5x7D04fq9H9PC+4coFLV/vry7tr1zYi/DPvW7KXzEP+lkvFO45oiwHdvBCFG/8kUpr8=
